### ISSUE TITLE
Create @types

### ISSUE THREAD

**Issue by Muurilo** [i18next/i18next-fs-backend#10]
## 🚀 Feature Proposal

The creation of the package with the types of the project, in the deprecated version there was but in this one, it is essential to have

## Motivation

Without this feature it is not possible to use this module with typescript without its types

## Example

This feature is for using the module with typescript. It's simple to do and essential

**Comment by adrai** [comment]
Feel free to submit a PR

**Comment by adrai** [comment]
//cc #3
