### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by Skillz4Killz** [i18next/i18next-fs-backend#11]
## 🐛 Bug Report

When using this for a Deno project, it can throw errors from inside this project. 
However, they are very odd errors.

![image](https://user-images.githubusercontent.com/23035000/91109466-0a6ae480-e649-11ea-9324-ee39ef1f2d65.png)

## To Reproduce

https://github.com/Skillz4Killz/gamer-deno

## Expected behavior

Not error saying it needs `require` and node typings in a deno project.

## Your Environment

- *runtime version*: deno
- *i18next version*: 19.6.3
- *os*: Mac (i've had window users also confirm the issue)
- This began happening when i added database support using DenoDB. https://github.com/eveningkid/denodb

**Comment by adrai** [comment]
Can you update your deno version and try this example?
https://github.com/i18next/i18next-fs-backend/tree/master/example/deno

`deno run --reload --allow-read --allow-write index.js`

**Comment by Skillz4Killz** [comment]
Hello 👋 I am using the latest Deno version. The example works fine. My entire project worked fine as well until DenoDB was added. As soon as that is run, i18next breaks for some weird reason. I have opened an issue on their repo in case this is a bug on their end but i opened it here as the errors were coming from i18next files. https://github.com/eveningkid/denodb/issues/100

**Comment by adrai** [comment]
I assume this is a Deno internal problem/change...
If you like, and know more about Deno, please open an issue on the Deno project as well.
