### ISSUE TITLE
loadPath array

### ISSUE THREAD

**Issue by QuantumlyTangled** [i18next/i18next-fs-backend#12]
## 🚀 Feature Proposal

Ability to pass an array of strings/paths to loadPath.

## Motivation

At the moment you can only load a single path or use a custom function to define a path but its still just one in the end. I wish to be able to layer different project paths and use them in a single i18next instance.

**Comment by adrai** [comment]
May I ask what the benefit would be?
How does your usecase look like?
How should the array be handled?
