### ISSUE TITLE
Support namespace with slashes (locale subdirectories)

### ISSUE THREAD

**Issue by haggen** [i18next/i18next-fs-backend#13]
## 🚀 Feature Proposal

I'd like to load namespaces from subdirectories within the locale path. i.e. `locales/en/a/b/c.json`. This can already be achieved by simply including a slash in the namespace name when using other backends like http.

## Motivation

Better locale files organization, grouping by subject or feature. Other backends like http already support it.

## Example

We could simply use slashes inside namespaces name. Right now slashes are being encoded. e.g. `a/b` tries to load `a&#x2F;b.json`.

**Comment by adrai** [comment]
I don't think this is a good idea, on the filesystem the "/" can be encoded in different ways...
for example in MacOS a "/" in the filename is encoded with ":"

**Comment by haggen** [comment]
Hi @adrai, thanks for the quick response.

I'm not sure I follow you. What I meant by "being encoded" is that right now a slash gets converted to an ampersand entity, which is what is breaking this feature. If that wasn't the case a slash in the namespace would work as I expected.

The odd thing is that other backends already support this. Which is specially jarring when using next-i18next since it depends on both backends. The final result is that SSR breaks translations but once the app is hydrated changing translations work as expected.

**Comment by adrai** [comment]
In theory the slash in namespace feature is not a "wanted" feature...
By keeping the slash as is, is exactly the problem I tried to describe in my last [comment](https://github.com/i18next/i18next-fs-backend/issues/13#issuecomment-720554116)...
Because a slash in a filename is handled differently in each filesystem/OS this will not work for everyone.

**Comment by haggen** [comment]
Oh ok got you. You're right. From my experience we're talking about Windows inverted slash, because AFAIK Linux and macOS both use the slash as directory separator. At any rate we could translate a slash in the namespace to the system appropriate directory separator.

**Comment by haggen** [comment]
Bottom line is I think being forced to put all the locale files in the same folder get really messy in larger applications. Right now on the project I'm working on we're already at the point we have to prefix the files.

**Comment by adrai** [comment]
Maybe having the loadPath option to be a function: https://github.com/i18next/i18next-fs-backend/blob/master/lib/index.js#L35 can be used for your use case to manipulate the resulting path...
![image](https://user-images.githubusercontent.com/1086194/97893904-27e7b900-1d32-11eb-8b36-9dec7a70b7d7.png)

**Comment by haggen** [comment]
@adrai I'll look into it. Thanks!

**Comment by haggen** [comment]
I managed to get it working with a 'loadPath()' function. It's not ideal though but I haven't figured out to which scope the issue  belongs (if it's the back-end or what). For now it'll do. Thanks.

**Comment by gijsbertsyntess** [comment]
> In theory the slash in namespace feature is not a "wanted" feature... By keeping the slash as is, is exactly the problem I tried to describe in my last [comment](https://github.com/i18next/i18next-fs-backend/issues/13#issuecomment-720554116)... Because a slash in a filename is handled differently in each filesystem/OS this will not work for everyone.

I'm sorry, but I think this is very much a wanted feature. The forward slash / works on Linux, MacOs and also on Windows (on Windows forward and backward slash both work, strange enough). So there is no real reason not to allow the forward slash as a separator. We have our translations stored in a nice file hierarchy, which works just fine with i18next-http-backend. We also want to use the same translation in the backend and would like to keep the file structure.

**Comment by adrai** [comment]
feel free to provide a PR
