### ISSUE TITLE
Not honouring hyphenated names when loading languages

### ISSUE THREAD

**Issue by Nytelife26** [i18next/i18next-fs-backend#14]
## 🐛 Bug Report
i18next does not seem to honour hyphenated directory names on my system when loading namespaces.  
My project works on Windows and MacOS, but does not seem to on my Arch Linux laptop.  

I have a language folder, located at `languages/en-us`. None of the keys are loading or resolving properly.  
In order to diagnose the issue I enabled debug in the i18n settings.

```js
i18next: initialized {
  debug: true,
  initImmediate: false,
  ns: [ 'core', 'fun', 'global', 'moderation', 'utilities' ],
  defaultNS: 'global',
  fallbackLng: [ 'en-us' ],
  fallbackNS: false,
  whitelist: false,
  nonExplicitWhitelist: false,
  supportedLngs: false,
  nonExplicitSupportedLngs: false,
  load: 'all',
  preload: [ 'en-us' ],
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
```
As you can see, it detects the namespaces and the language just fine in the initialization.  
However, when loading the language,

```js
i18next::backendConnector: loading namespace utilities for language en failed Error: ENOENT: no such file or directory, open '/home/nytelife26/projects/syrus-bot/src/languages/en/utilities.json'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at readFileInNodeSync (/home/nytelife26/projects/syrus-bot/node_modules/i18next-fs-backend/cjs/readFile.js:30:13)
    at readFileSync (/home/nytelife26/projects/syrus-bot/node_modules/i18next-fs-backend/cjs/readFile.js:102:12)
    at Backend.read (/home/nytelife26/projects/syrus-bot/node_modules/i18next-fs-backend/cjs/index.js:71:54)
    at Connector.read (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1583:34)
    at Connector.loadOne (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1641:12)
    at /home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1617:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1616:21)
    at Connector.load (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1623:12)
    at I18n.loadResources (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1975:40)
    at setLng (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:2071:16)
    at I18n.changeLanguage (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:2081:9)
    at load (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1917:16)
    at I18n.init (/home/nytelife26/projects/syrus-bot/node_modules/i18next/dist/cjs/i18next.js:1929:9) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/nytelife26/projects/syrus-bot/src/languages/en/utilities.json'
}
```
It removes the hyphenated section of the name. This is unexpected behaviour.

## To Reproduce

1. Use i18n on a UNIX system similar to mine
2. Create a language directory with a hyphenated name
3. Get i18n to attempt to load the namespaces

```js
i18n: {
	defaultMissingKey: "missing",
	defaultNS: "global",
	i18next: {
		preload: ["en-us"],
		load: "all",
		fallbackLng: "en-us",
		initImmediate: false,
		interpolation: {
			escapeValue: false
		}
	}
}
```

## Expected behavior

I expected i18n to load the language with the full name, honouring the hyphen.

## Your Environment

- *runtime version*: node v14.x
- *i18next version*: 19.8.3
- *os*: Arch Linux

**Comment by adrai** [comment]
In the error you're trying to load: "languages/en/utilities.json"
but you are saying you have "languages/en-us/utilities.json"

probably you should change the load option to: currentOnly

**Comment by Nytelife26** [comment]
@adrai Yup, that seems to be it. To note though, additionally I needed to set `lowerCaseLng: true` as well.
This does pose the question, though - why does it automatically transform input values? Surely it should load what it's told to, with no magical unexpected transformations?

**Comment by adrai** [comment]
i18next formats the language: https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L36

**Comment by Nytelife26** [comment]
...so when I asked about this and I was told to move it to a backend lib, that was actually unnecessary because the format splitting by hyphen IS because of the core i18next library?

Ah well. This should probably be transferred back, then, because automatically splitting the language name by hyphen and formatting without being explicitly enabled should classify as unexpected behaviour.

**Comment by Nytelife26** [comment]
I have established that the cause of this issue with platform differences is that on Windows, folder names are not case sensitive, whereas on UNIX-like systems, this is not the case. Therefore automatically switching the case of the folder names or reformatting them or similar creates unexpected behavior on some systems, which is not ideal. Can this be changed?

It is important to note that largely, reformatting input should be opt-in, not out - and usually not an option at all, it should largely be down to the end user to handle their own locale name formatting, as it is not the library's place nor responsibility.
For more on that last note, see: "UNIX Style, or cat -v Considered Harmful"

**Comment by adrai** [comment]
The documentation tells how language codes should look like: https://www.i18next.com/principles/translation-resolution#languages maybe the documentation should be more clear?

**Comment by Nytelife26** [comment]
Perhaps, or alternatively i18next should avoid standardization and forcing / assuming a specific format and rather use the language names it is given, with automatic formatting checking being opt-in rather than default behaviour.

**Comment by adrai** [comment]
maybe in the next major refactoring 🤷‍♂️

**Comment by Nytelife26** [comment]
The behaviour of the library is incongruent with the documentation. That has two resolutions:
1. Change the documentation to match the behaviour
2. Change the behaviour to match the documentation

Having reviewed the documentation, it describes exactly what should happen - i18next should use the language keys provided, or if those are missing, use the fallback. Therefore, the latter resolution is the ideal, and the one that should be implemented to fix this unexpected behaviour.

**Comment by adrai** [comment]
Feel free to contribute with a PR without breaking all existing plugins and extensions in the current ecosystem.

**Comment by Nytelife26** [comment]
Should I make another issue reformatting this as a refactoring request, with proposed solutions and rationales?

My primary reasoning for this is that it breaks the internationalization on UNIX systems without opting-out, since their filesystems are case sensitive, which should not be the default behaviour. The default behaviour should be to use exactly the keys given, with reformatting either being opt-in or not part of the library at all.

**Comment by adrai** [comment]
i18next exists with that language formatting since 10 years.
I don't think this can be changed without impact for the ecosystem.
If you see a possibility that will not hurt, feel free.

**Comment by Nytelife26** [comment]
@adrai i18next has automatically changed the formatting of whatever keys you give it for 10 years?
It has never once from the start just accepted the values it's given and used those, with the option to enable automatically splitting and capitalizing the string, ever?

**Comment by jamuhl** [comment]
@Nytelife26 You're using a module coming for free, which made the decision to follow the convention of having locales in the form `lng-Script-REGION`. This might be non-optimal for your case - but is the best option for most users. If your filesystem is case sensitive just name the folders as requested.

**Comment by Nytelife26** [comment]
@jamuhl It is not that this is non-optimal for my case, but rather that the conventions should be opt-in, not imposed. It is not the place of the library to impose a required structure, nor is it the place of the library to make breaking conversions the default behaviour. 

The point being that nobody should have to rename their project folders to use a module - it should operate on what it is given. Modules are meant to be tools to assist programmers in building applications - nothing more. Conventions are not your place to impose.

**Comment by jamuhl** [comment]
I disagree - but will not go for an endless discussion...it's OSS, it's free, no one forces you to use it.
