### ISSUE TITLE
TypeError: fs.readFileSync

### ISSUE THREAD

**Issue by NiloDrumond** [i18next/i18next-fs-backend#16]
Hi,

Im having the following problem when I start my react app:

``i18next::backendConnector: loading namespace backend-app for language en failed TypeError: fs.readFileSync is not a function``

https://gist.github.com/NiloDrumond/92ff755e77e57a6ed2e9d0dc591c96c3

Here is my i18n config file:

```import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import Backend from 'i18next-fs-backend';

i18n
  .use(Backend)
  .use(initReactI18next)
  .init({
    debug: true,
    initImmediate: false,
    fallbackLng: 'en',
    lng: 'en',
    preload: ['en'],
    ns: 'backend-app',
    defaultNS: 'backend-app',
    backend: {
      loadPath:
        process.env.NODE_ENV !== 'production'
          ? `./locales/{{lng}}/{{ns}}.json`
          : ` ./app/locales/{{lng}}/{{ns}}.json`,
    },
    react: {
      useSuspense: false, // https://stackoverflow.com/questions/59464880/how-to-fix-no-fallback-ui-was-specified-in-react-i18next-using-hooks
    },
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });

export default i18n;
```
I also get this warning after: ``./node_modules/i18next-fs-backend/esm/readFile.js
Critical dependency: the request of a dependency is an expression``

versions:
- "i18next": "^19.8.4",
- "i18next-fs-backend": "^1.0.7",
- "react-i18next": "^11.8.5",
- "@types/i18next-fs-backend": "^1.0.0",
- "typescript": "4.0.3",

In another project, I use i18next-http-backend with no problem, but as in this project I'm using electron, I choose to use fs instead, but I still haven't managed to make it work.

Thanks!

**Comment by adrai** [comment]
Are you using react on server side?

Can you please create a reproducable example?

**Comment by NiloDrumond** [comment]
> Are you using react on server side?
> 
> Can you please create a reproducable example?

1. npx create-react-app app --template=typescript
2. yarn add i18next i18next-fs-backend react-i18next
3. yarn add -D @types/i18next-fs-backend
4. create i18n.ts like I posted here and import in index.tsx
5. create sample translation: src/locales/en/transaltion.json
6. yarn start

Same error.

I created this repo just to reproduce this problem:
https://github.com/NiloDrumond/fs-backend-error

@adrai 

I just saw your edit. It actually makes sense, but I thought it would work on electron at least, but I get the same error.
I suppose I will try the http-backend for electron.

**Comment by adrai** [comment]
> I created this repo just to reproduce this problem:

Yes, this does not look to be executed on server side...

> I just saw your edit. It actually makes sense, but I thought it would work on electron at least, but I get the same error.
I suppose I will try the http-backend for electron.

Personally, I never tried electron, but if it has not the node.js fs api, it will not to work.
