### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by reZach** [i18next/i18next-fs-backend#17]
## 🐛 Bug Report

When trying to pull a translation for a key that does not exist, I am receiving a `Maximum call stack size exceeded` error.

## To Reproduce

```
git clone https://github.com/reZach/secure-electron-template.git
git checkout broken-menu-translation
npm i
npm run dev
```
Notice error in console.

## Expected behavior
The app does not throw any errors and successfully creates keys with value "File" in my various translation json files.

## Additional details
I am trying to translate Electron menu items based off of [this tutorial](https://phrase.com/blog/posts/building-an-electron-app-with-internationalization-i18n/). I am creating the Electron menu _after_ changing the i18n language as shown below:

**main.js**
```js
  menuBuilder = MenuBuilder(win, app.name);

  i18nextMainBackend.on("loaded", (loaded) => {
    i18nextMainBackend.changeLanguage("en");
    i18nextMainBackend.off("loaded");
  });

  i18nextMainBackend.on("languageChanged", (lng) => {
    i18nextMainBackend.changeLanguage(lng);
    menuBuilder.buildMenu(i18nextMainBackend); // build electron menu
  });
```

I am trying to generate new translation entries for a new key "File". This is the menu item in my electron app:
**menu.js**
```js
{
        label: i18nextMainBackend.t("File"),
        submenu: [
          isMac
            ? {
                role: "close"
              }
            : {
                role: "quit"
              }
        ]
      },
```

I do find an existing entry in my translation file, but then the **RangeError: Maximum call stack size exceeded** error is thrown
```
[1] i18next::backendConnector: loaded namespace translation for language en { Hello: 'Hello' }
[1] i18next::backendConnector: loading namespace translation for language en failed RangeError: Maximum call stack size exceeded
[1]     at String.indexOf (<anonymous>)
[1]     at ResourceStore.getResource (C:\Users\me\source\repos\secure-electron-template\node_modules\i18next\dist\cjs\i18next.js:356:15)
[1]     at ResourceStore.hasResourceBundle (C:\Users\me\source\repos\secure-electron-template\node_modules\i18next\dist\cjs\i18next.js:438:19)
```

## Your Environment

- *runtime version*: i.e. node v12.14.0
- *i18next version*: i.e. 19.8.7
- *os*: Windows

**Comment by adrai** [comment]
I don't think i18next-fs-backend is a dependency here...
btw: I suspect this is generating the loop... on languageChanged event of i18next, you tell i18next to change language, which will retrigger a languageChanged, etc...

```js
  i18nextMainBackend.on("languageChanged", (lng) => {
    i18nextMainBackend.changeLanguage(lng);
    menuBuilder.buildMenu(i18nextMainBackend); // build electron menu
  });
```

**Comment by reZach** [comment]
> 
> 
> I don't think i18next-fs-backend is a dependency here...
> btw: I suspect this is generating the loop... on languageChanged event of i18next, you tell i18next to change language, which will retrigger a languageChanged, etc...
> 
> ```js
>   i18nextMainBackend.on("languageChanged", (lng) => {
>     i18nextMainBackend.changeLanguage(lng);
>     menuBuilder.buildMenu(i18nextMainBackend); // build electron menu
>   });
> ```

Can't believe I didn't see this, thank you for your sharp eyes @adrai!
