### ISSUE TITLE
i18next do not complain when wrong `loadPath` is given

### ISSUE THREAD

**Issue by fxmarty** [i18next/i18next-fs-backend#19]
## 🐛 Bug Report

`loadPath` seem not to be taken into account, and whether the path is valid or not the behavior is the same.

## To Reproduce

Run:

```js
const i18next = require('i18next')
const backend = require('i18next-fs-backend')

const options = {
    lng: 'en',
    fallbackLng: 'en',
    loadPath: '/path/is/wrong/translation.json',
}

i18next.use(backend).init(options)

// sleep time expects milliseconds
function sleep (time : number) {
    return new Promise((resolve) => setTimeout(resolve, time));
}

sleep(300).then(() => {
    console.log(i18next.languages)
    console.log(i18next.language)
    console.log(i18next.dir())
    console.log(i18next.exists('mykey.mymessage'))
});
```

The code executes well and returns exit code 0, output:

```
[ 'en' ]
en
ltr
false
```

Additionally, setting `loadPath` to the real path, e.g. `locales/en/translation.json`, still compiles well but the output is the same, even if my key `mykey.mymessage` does exist in my `translation.json` file:

```
{
  "mykey": {
    "mymessage": "hehe",
    "description": "haha"
  }
}
```

Then, this is very hard to debug because you don't know whether the problem is that your json file is not loaded, of if it is something else.

## Expected behavior

I would expect having an error because the path I give is wrong.

## Your Environment

- *runtime version*: node 14.15.5
- i18next-fs-backend@1.1.0
- i18next@19.9.2
- *os*: Linux

**Comment by adrai** [comment]
it's intended to work like this...
i.e. what if you request a language you do not have on fs?

set debug to true to see the "warning"

**Comment by fxmarty** [comment]
First thing I realize is that my syntax is wrong above, it should be
```
const options = {
    lng: 'en',
    fallbackLng: 'en',
    backend: {
        loadPath: 'locales/{{lng}}/{{ns}}.json',
    }
}
```
and not
```
const options = {
    lng: 'en',
    fallbackLng: 'en',
    loadPath: 'locales/{{lng}}/{{ns}}.json',
}
```

I think it would be healthier to have exception handling by the user himself if he requests a file that is not on disk. But it is maybe a problem of `fs`. As I am new to JavaScript, maybe I am used to being thrown a lot of errors so that I know *from the start* why something does not work.

Anyway, thanks a lot for your help `debug` does the trick!
