### ISSUE TITLE
Feature Request: Support callback for loadPath option

### ISSUE THREAD

**Issue by ckeeney** [i18next/i18next-fs-backend#2]
It would be great if the loadPath option could be passed a callback function that takes namespace and language.

## Motivation
We received about 50 responses to a questionnaire we sent out and we would like to show these Q&A on our site.  The questionnaire is quite long, so I plan on making each response it's own namespace.  

I have everything working, but now I have about 15 namespaces (translation files) for my website and 50 namespaces for my questionnaire responses.  I'd like to put all these in a single folder in my `locales` folder and use the `loadPath` option customize the load path just for the questionnaire responses so I can have `/locales/en/common.json`, `/locales/en/homepage.json`, and `/locales/en/question-responses/person-1.json`...

**Comment by adrai** [comment]
I don't know exactly what you like to do...
Currently the loadPath can be a function: function(lng, namespace) { return customPath; }
So if you're able to return a customPath based on language and namespace, that should already work.

**Comment by ckeeney** [comment]
Whoops you are right, this is already supported.  
Thanks for the great library!
