### ISSUE TITLE
Create type definitions

### ISSUE THREAD

**Issue by pedrodurek** [i18next/i18next-fs-backend#20]
## 🚀 Feature Proposal
For now, there are no type definitions for `i18next-fs-backend`. This issue is just for reference, I'm going to work on it as soon as I can.

**Comment by mad-it** [comment]
I just found these types: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/i18next-fs-backend
Do they belong to this project? 🤔

**Comment by adrai** [comment]
looks like, but not created and not maintained by “us”

**Comment by medihack** [comment]
Since the latest release of `i18next-http-backend` (since 1.2.0) I also get the below Typescript error when setting the `loadPath` option and using `i18next-http-backend` and `i18next-fs-backend` in the same app. I double-checked the parameters of my custom `loadPath` handler and the parameters are not arrays but just a string for `lng` and `ns`. I tried it with and without the DefinitlyTyped types.

```
No overload matches this call.
  Overload 1 of 2, '(callback?: Callback | undefined): Promise<TFunction>', gave the following error.
    Argument of type '{ backend: { loadPath: (lng: string, ns: string) => string; }; }' is not assignable to parameter of type 'Callback'.
      Object literal may only specify known properties, and 'backend' does not exist in type 'Callback'.
  Overload 2 of 2, '(options: InitOptions, callback?: Callback | undefined): Promise<TFunction>', gave the following error.
    Type '(lng: string, ns: string) => string' is not assignable to type 'LoadPathOption | undefined'.
```

**Comment by adrai** [comment]
If using with multiload, they are arrays

**Comment by adrai** [comment]
i18next-http-backend passes arrays and i18next-fs-backend passes strings

**Comment by medihack** [comment]
Yes, I know. But unfortunately, Typescript doesn't seem to know, or better to say, mistakes types.

```
import i18n from "i18next"
import Backend from "i18next-fs-backend"
...
const createClient = () => {
  const instance = i18n.createInstance()

  // here is where the TS error appears
  const initPromise = instance.use(Backend).init({ backend: { loadPath } })
  return { i18n: instance, initPromise }
}

function loadPath(lng: string, ns: string) {
  ...
  return path
}
```

**Comment by daniellwdb** [comment]
It would be nice to see template literal types being used like [react-i18next](https://react.i18next.com/latest/typescript)

**Comment by adrai** [comment]
v1.2.0 should now include the types directly for i18next < v22.0.0
and v2.0.0 should now include the types directly for i18next >= v22.0.0
