### ISSUE TITLE
License filed format

### ISSUE THREAD

**Issue by sosoba** [i18next/i18next-fs-backend#21]
Hello. Your `package.json` has a `license` field with [deprecated style](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license).

Currently `npm` tool says that your package are proprietary 
```
npm info i18next-fs-backend

i18next-fs-backend@1.1.1 | Proprietary | deps: none | versions: 12
```

Together view https://www.npmjs.com/package/i18next-fs-backend say:  License none

**Comment by adrai** [comment]
aha... I did not know this was not supported anymore... thx for the info... the next release will have this fixed.
