### ISSUE TITLE
Fluent Support

### ISSUE THREAD

**Issue by obermillerk** [i18next/i18next-fs-backend#22]
## 🚀 Feature Proposal

I would love to see this support the Fluent format!

## Motivation

Wanted to use fluent while loading files from the filesystem, but alas this backend does not support it, and there is no fluent filesystem backend that I could see (apart from possibly using `file://` requests in the XHR fluent backend, but I'm not sure that would even work and doesn't feel great regardless).

## Example

Use it to load `.FTL` files for Fluent translations.

**Comment by adrai** [comment]
Feel free to provide a PR that will work with no dependencies for Node.js and Deno.

**Comment by jamuhl** [comment]
Did you already have a look at: https://github.com/i18next/i18next-fluent

**Comment by obermillerk** [comment]
I did try dropping in the `i18next-fluent` plugin, to no avail. Tried with my normal json file with fluent syntax for the entries, and also tried converting to a proper fluent file (which I then saw is not supported by this backend) which also didn't work.

I looked at the backend as well, but as stated in the original issue I'm loading from filesystem and that backend is using ajax requests. I'm not sure if ajax requests would support `file://` protocol, but I think I've had trouble with that in the past, and besides feels like bad practice even if it would work.

I might be missing something, but seems like there isn't a way to load the files from filesystem at the moment. Maybe this would fit better elsewhere, but thought this plugin was named generically enough that you might consider adding the support here.

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/react-fluent/src/i18n.js

**Comment by obermillerk** [comment]
Third time, that is using ajax requests to load the files.

**Comment by jamuhl** [comment]
@obermillerk there currently is no fluet backend for filesystem...but you can easily create your own...my point is having a backend is not enough...and backend plugins are easy to create (that's why those are plugins)

**Comment by obermillerk** [comment]
Fair enough. I've already gone back to normal json syntax anyway at this point, so I guess it doesn't matter much regardless at this point. Just saw a gap in functionality in your ecosystem, thought I'd suggest patching it up.

**Comment by jamuhl** [comment]
not everything gets maintained by us. fluent as an option is like the option to use ICU -> we're happy for support from the community there (but as we don't use that ourself - it won't be our focus...)

**Comment by adrai** [comment]
If you like, you can also extend i18next-fs-backend, but it needs to work also in Deno.
