### ISSUE TITLE
When reloading resources removed keys are still being returned

### ISSUE THREAD

**Issue by sabbaghAtKait** [i18next/i18next-fs-backend#23]
I am using i18next, i18next-fs-backend, i18next-http-middleware to support i18. we are loading the transition files when the app starts, then we reloadResources on demand. it happen that some keys have been removed from the resources. but still when we are req.t() getting back the translation for the deleted key!

## To Reproduce

1) download code https://codesandbox.io/s/little-night-n5yi4?file=/src/index.js
2) npm start
3) hit http://localhost:3001/api/translation/flush you should get (Translation EN)
4) update translation.success in translation.json 
5) hit http://localhost:3001/api/translation/flush you should get the new updated value i.e (updated Translation EN)
6) update translation.success node name to be foo.bar
5) hit http://localhost:3001/api/translation/flush you should get foo.bar as there is no translation 

```js
(async () => {
  await i18next
    .use(backend)
    .use(i18nextMiddleware.LanguageDetector)
    .init({
      backend: {
        loadPath: __dirname + "/../locales/{{lng}}/{{ns}}.json"
      },
      fallbackLng: "en",
      debug: true
    });
})();

app.use(i18nextMiddleware.handle(i18next));

module.exports.reloadTranslation = () => {
  try {
    return i18next.reloadResources(["en", "ko"]);
  } catch (e) {
    console.log(e);
  }
};

```

- *runtime version*:  node v14
- *i18next version*: 20.6.1
- *os*:  Windows,

**Comment by adrai** [comment]
reloadResources does not clear the i18next store....
try to do this: `i18next.store.data = {};`
![image](https://user-images.githubusercontent.com/1086194/133121834-aa36c531-e46f-411f-a32d-098f1350e1fb.png)

**Comment by sabbaghAtKait** [comment]
@adrai this resolve the issue but there is another issue:

STR: 
1) npm start
2) hit http://localhost:3001/api/translation/flush you should get (Translation EN)
3) delete translation.success in translation.json
4) hit http://localhost:3001/api/translation/flush you should get the (translation.success)
5) add translation.success node name to translation.json
6) hit http://localhost:3001/api/translation/flush you should get (Translation EN) but you will get (translation.success)

**Comment by adrai** [comment]
> @adrai this resolve the issue but there is another issue:
> 
> STR:
> 
> 1. npm start
> 2. hit http://localhost:3001/api/translation/flush you should get (Translation EN)
> 3. delete translation.success from translation.json
> 4. hit http://localhost:3001/api/translation/flush you should get the (translation.success)
> 5. add translation.success key to translation.json
> 6. hit http://localhost:3001/api/translation/flush you should get (Translation EN) but you will get (translation.success)

sorry I'm not able to reproduce this with the `i18next.store.data = {};` hack

**Comment by adrai** [comment]
So can this issue be close @sabbaghAtKait ?

**Comment by sabbaghAtKait** [comment]
@adrai this is not happening directly try after a couple of requests with large translation files. also am resolving the lang based on accept-language header

**Comment by adrai** [comment]
[reloadResources](https://www.i18next.com/overview/api#reloadresources) is asynchronous, so it may be you need to wait somewhere...

**Comment by sabbaghAtKait** [comment]
@adrai added await and still the same. will work in getting STR
