### ISSUE TITLE
cannot find module './path.cjs' in version 1.1.2

### ISSUE THREAD

**Issue by JoweiBlog** [i18next/i18next-fs-backend#25]
## 🐛 Bug Report

cannot find module './path.cjs' in version 1.1.2

## To Reproduce

Error: Cannot find module './path.cjs'
Require stack:
- /Users/test/home/project/website/node_modules/i18next-fs-backend/cjs/readFile.js
- /Users/test/home/project/website/node_modules/i18next-fs-backend/cjs/index.js

## Expected behavior

'./path.js'

## Your Environment

- i18next version 20.6.1
- i18next-fs-backend version 1.1.2

**Comment by zhengissov** [comment]
Same here:
UnhandledPromiseRejectionWarning: Error: Cannot find module './path.cjs'

**Comment by adrai** [comment]
I know why...
missed to change a script in the package.json
currently afk, will fix asap
