### ISSUE TITLE
Cannot find module './path.cjs' in ESM version 1.1.3

### ISSUE THREAD

**Issue by 36serg6** [i18next/i18next-fs-backend#26]
## 🐛 Bug Report

Cannot find module './path.cjs' in version 1.1.3 (esm)

Maybe you should also update the "compile:esm" script in package.json. Because there was a similar issue for cjs in previous version: https://github.com/i18next/i18next-fs-backend/issues/25

## To Reproduce

Error: Cannot find module './path.cjs' imported from /esm/readFile.js
Require stack:

- /Users/test/home/project/website/node_modules/i18next-fs-backend/cjs/readFile.js
- /Users/test/home/project/website/node_modules/i18next-fs-backend/cjs/index.js

## Expected behavior

In files /esm/readFile.js and /esm/writeFile.js should import 

- ./fs.js instead ./fs.cjs
- ./path.js instead ./path.cjs

Then the error goes away.

## Your Environment

- Node.js version v14.17.3
- i18next version 21.4.2
- i18next-fs-backend version 1.1.3

**Comment by adrai** [comment]
You're right... I'm sorry
should be fixed with v1.1.4

**Comment by 36serg6** [comment]
Thanks @adrai , everything works fine now ^^
