### ISSUE TITLE
Bug in readFile.js when a label has a semicolon present in it

### ISSUE THREAD

**Issue by karanpvyas** [i18next/i18next-fs-backend#29]
## 🐛 Bug Report

If a particular namespace.js file has some value with a semicolon in it, the `eval` done after [readFile.js#L67](https://github.com/i18next/i18next-fs-backend/blob/master/lib/readFile.js#L67) fails.

Example namespace.js file:
`
export default {
   headerKey: "This is the header; This is YOUR header!"
};
`

Since the replacement of `;` happens within the label itself, the `;` at the EOF is not replaced, and `eval` done just after it fails.

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by adrai** [comment]
should be a bit better with v1.1.5
