### ISSUE TITLE
Rollup bundler complains about eval() usage

### ISSUE THREAD

**Issue by crystalfp** [i18next/i18next-fs-backend#37]
## 🐛 Bug Report

Rollup bundler complains about `eval()` usage in the `i18next-fs-backend` code.

The simple change needed to avoid this and to increase security is explained on the [rollup page](https://rollupjs.org/troubleshooting/#eval2-eval).

## To Reproduce
Bundle the following code (ex.js)
```js
import i18next from "i18next";
import FsBackend from "i18next-fs-backend";
i18next .use(FsBackend)
```
using `npx rollup -c` with this `rollup.config.js`:
```
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import terser from "@rollup/plugin-terser";
import json from "@rollup/plugin-json";

export default {
	input: "ex.js",
	output: {
		file: "dist/bundle.js",
		format: "es",
		sourcemap: true,
	},
	plugins: [
		json(),
		resolve({preferBuiltins: true}),
		commonjs(),
		terser()
	]
};
```
The warning is the following:
```
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules/i18next-fs-backend/esm/readFile.js
86:         }
87:       }
88:       result = eval(data);
                   ^
89:       break;
90:     case '.json5':
```

## Expected behavior

1) stop rollup bundler complaining
2) increase security (see the cited page)

## Your Environment

- *runtime version*:  node v19.8.1
- *i18next version*:  22.5.0
- *os*: Windows
- *i18next-fs-backend*: 2.1.2

**Comment by adrai** [comment]
Can you try with v2.1.3 ?

**Comment by crystalfp** [comment]
Solved! Thanks

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
