### ISSUE TITLE
`i18next-fs-backend` fails to update cache

### ISSUE THREAD

**Issue by theabdulmateen** [i18next/i18next-fs-backend#38]
## 🐛 Bug Report

I am using `next-i18next` with `i18next-chained-backend` for `i18next-fs-backend` & `i18next-http-backend` in a Next.js app, where `i18next-fs-backend` is used as [server-side cache](https://www.i18next.com/how-to/caching#server-side-next.js-caching-with-filesystem).

It seems like there is an issue with the updation of cache, from my understanding when the `expirationTime` exceeds `i18next-http-backend` fetches the latest locales from the API and `i18next-fs-backend` removes the locales present in `loadPath` and adds the fetched locales in `addPath` essentially replacing the locales present in the filesystem with the latest one.

The plugin is able to remove the locales from `loadPath` but after fetching the latest locales from API, it does not add it to `addPath`.

I am also using the custom request option as seen here in my `next-i18next.config.js`:

```javascript
const axios = require('axios');
const ChainedBackend = require('i18next-chained-backend');

/**
 * @type {import('next-i18next').UserConfig}
 */
module.exports = {
  // debug: process.env.NODE_ENV === 'development',
  // reloadOnPrerender: process.env.NODE_ENV === 'development',
  debug: true,
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es', 'zh'],
  },
  lng: 'en',
  fallbackLng: 'en',
  preload: ['en', 'es', 'zh'],
  ns: ['common'],
  defaultNS: 'common',
  backend: {
    backends:
      typeof window === 'undefined'
        ? [
            require('i18next-fs-backend/cjs'),
            require('i18next-http-backend/cjs'),
          ]
        : [],
    backendOptions:
      typeof window === 'undefined'
        ? [
            {
              loadPath: './public/locales_cache/{{lng}}/{{ns}}.json',
              addPath: './public/locales_cache/{{lng}}/{{ns}}.json',
              // expirationTime: 60 * 1000 * 60, // 1 hour
              expirationTime: 60 * 1000 * 2, // 2 min
            },
            {
              loadPath: '{{lng}}/{{ns}}.json',
              request: async (_options, url, _payload, callback) => {
                try {
                  const [locale] = url.split('/');
                  const result = await axios(
                    `${process.env.NEXT_PUBLIC_API_URL}/contents/webapp_content/`
                  );
                  const content = result.data[locale] || {};

                  callback(null, { status: 200, data: content });
                } catch (error) {
                  callback(error, null);
                }
              },
            },
          ]
        : [],
  },
  use: typeof window === 'undefined' ? [ChainedBackend] : [],
  react: {
    useSuspense: false,
  },
  returnNull: false,
  serializeConfig: false,
};

```

The config is also passed to pages that use SSR and SSG like so:
```typescript
// src/pages/index.tsx

import React from 'react';

import { GetServerSideProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import { Landing } from '@/containers/Landing/Landing';
import { Layout } from '@/layout/Layout';

import nextI18nConfig from '../../next-i18next.config.js';

export default function LandingPage() {
  return (
    <Layout>
      <Landing />
    </Layout>
  );
}

export const getServerSideProps: GetServerSideProps = async ({
  locale = 'en',
}) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'], nextI18nConfig)),
    },
  };
};
```

## To Reproduce

Please try the config mentioned above

## Expected behavior

It should update the cache after fetching the latest locales

## Your Environment

- *runtime version*: node v18.16.0
- *os*: Linux
- *i18next*: ^22.5.1
- *i18next-chained-backend*: ^4.3.0
- *i18next-fs-backend*: ^2.1.3
- *i18next-http-backend*: ^2.2.1
- *react-i18next*: ^12.3.1
- *next-i18next*: ^12.1.0

**Comment by adrai** [comment]
This example shows that it works: https://github.com/i18next/i18next-fs-backend/tree/master/example/caching
So it must be something in your project.
Please set up a minimal github repo showing your issue.

**Comment by theabdulmateen** [comment]
Okay I think I found the issue, I get the following error when the locale file has keys `foo` along with `foo.bar`:
```
> node app.js
Welcome
Welcome
/home/meeexy/Documents/dev//i18next-server-side-cache-test/node_modules/i18next-fs-backend/cjs/utils.js:60
  obj[k] = newValue;
         ^

TypeError: Cannot create property 'description' on string 'Welcome'
    at setPath (/home/meeexy/Documents/dev/i18next-server-side-cache-test/node_modules/i18next-fs-backend/cjs/utils.js:60:10)
    at /home/meeexy/Documents/dev/i18next-server-side-cache-test/node_modules/i18next-fs-backend/cjs/index.js:161:32
    at Array.forEach (<anonymous>)
    at proceed (/home/meeexy/Documents/dev/i18next-server-side-cache-test/node_modules/i18next-fs-backend/cjs/index.js:159:20)
    at /home/meeexy/Documents/dev/i18next-server-side-cache-test/node_modules/i18next-fs-backend/cjs/index.js:173:18

Node.js v18.16.0
```

`locales/en/translation.json`
```json
{
  "welcome": "Welcome",
  "welcome.description": "Lorem ipsum dolor sit amet consectetur adipisicing elit."
}
```

This is because the plugin interprets the `.` as a nested property and so when it parses the second key it cannot add the property `description` on type string
```json
{
  "welcome": "Welcome", // cannot add property "description" here since "welcome" is a string
}
```

Would it be possible to not have the keys formatted as such when the plugin updates the cache here? The alternative would be to update the keys everywhere in the whole app which is not feasible for us

**Comment by theabdulmateen** [comment]
Let me know if you'd still like me to create a minimal github repo for this

**Comment by adrai** [comment]
Please try with v2.1.4

**Comment by theabdulmateen** [comment]
That works! thank you for the quick response. much appreciated!

**Comment by theabdulmateen** [comment]
One question though, is `reloadOnPrerender` necessary for having the cache updated with http-backend? It seems that the cache is still not updated without it on SSR. What is the best way of setting up the interval with `next-18next` - similar to the example you mentioned.

**Comment by adrai** [comment]
If Next.js does not execute the serverSideTranslations function (in getStaticProps or getServerSideProps) the i18next backend will never be triggered. There's not much we can do here... sorry.

**Comment by theabdulmateen** [comment]
I see so does that means with this cache setup `reloadOnPrerender` is required to be set to true?

**Comment by adrai** [comment]
I'm not a Next.js expert... maybe there's an alternative... if not then yes.

**Comment by theabdulmateen** [comment]
Understood, thank you.

**Comment by theabdulmateen** [comment]
Oh and about the previous key flattening issue, when `foo` is an array (e.g. of objects), `foo.bar` is ignored and that is scary.

```json
{
  "welcome": [{ "label": "Welcome" }],
  "welcome.description": "Lorem ipsum dolor sit amet consectetur adipisicing elit."
}
```

It is parsed as 
```json
{
  "welcome": [
    {
      "label": "Welcome"
    }
  ]
}
```

```shell
node app.js
key 'welcome (en)' returned an object instead of string.
Welcome
key 'welcome (en)' returned an object instead of string.
Welcome
key 'welcome (en)' returned an object instead of string.
Welcome
key 'welcome (en)' returned an object instead of string.
Welcome
key 'welcome (en)' returned an object instead of string.
Welcome
key 'welcome (en)' returned an object instead of string.
Welcome
^C
```

**Comment by adrai** [comment]
you have a strange json structure, but ok... try with v2.1.5

**Comment by theabdulmateen** [comment]
Haha yes, it is quite absurd, I have cleaned up my json structure as well. 2.1.5 fixes it also, thanks.

**Comment by theabdulmateen** [comment]
Also, is there a `reloadOnInterval` feature similar to `reloadOnPrerender` in `next-i18next` which would go hand in hand with `expirationTime` of the cache layer?

**Comment by adrai** [comment]
> Also, is there a `reloadOnInterval` feature similar to `reloadOnPrerender` in `next-i18next` which would go hand in hand with `expirationTime` of the cache layer?

no
