### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by agoenks29D** [i18next/i18next-fs-backend#39]
## 🐛 Bug Report

I got an error message : "Argument of type 'typeof import("/node_modules/i18next-fs-backend/index")' is not assignable to parameter of type 'Module | NewableModule<Module> | Newable<Module>'."

```ts
import * as i18nextConfig from './config/i18next.config';
import * as I18NexFsBackend from 'i18next-fs-backend';
import { BackendModule } from 'i18next';

const t = await i18next.use(I18NexFsBackend).init(i18nextConfig);
```

## Environment

- *runtime version*: node v18.16.0
- *i18next version*: ^23.2.6

**Comment by adrai** [comment]
Not able to reproduce it, can you please provide a reproducible github repo?

**Comment by adrai** [comment]
also these tests seems to work: https://github.com/i18next/i18next-fs-backend/blob/master/test/typescript/basic.test-d.ts

**Comment by agoenks29D** [comment]
I am using Nest.js and enable debug mode.

Here was loaded
![image](https://github.com/i18next/i18next-fs-backend/assets/11814324/4479b5ef-22a6-4f7f-bbaa-879e9b690cd4)

But when i trying to use it
![image](https://github.com/i18next/i18next-fs-backend/assets/11814324/593e1b78-b87d-4620-a18e-2624c1ce43e6)

**Comment by adrai** [comment]
Read the first warning in your logs...
set lng to en or id or at least fallbackLng to en or id

**Comment by agoenks29D** [comment]
Yeaah thank you so much, it's work but another problem is `I18NexFsBackend` not not assignable to parameter of type 'Module | NewableModule<Module> | Newable<Module>'

**Comment by adrai** [comment]
Like said... provide a reproducible GitHub repo, so I can check.

**Comment by agoenks29D** [comment]
Here for example : https://github.com/agoenks29D/i18next-nest.js.git

**Comment by adrai** [comment]
set `"esModuleInterop": true`

**Comment by agoenks29D** [comment]
Thank you sir 👍🏻
