### ISSUE TITLE
Typescript error (running on Firebase Functions): You are passing an undefined module

### ISSUE THREAD

**Issue by ubuntudroid** [i18next/i18next-fs-backend#40]
## 🐛 Bug Report

Getting "You are passing an undefined module! Please check the object you are passing to i18next.use()" error at runtime when using Typescript for writing Firebase Functions.

## To Reproduce

1. Set up a Firebase Functions project (see Notes section further down)
2. Install the library using `npm install i18next-fs-backend`
3. Import the library:
```typescript
import I18NexFsBackend from "i18next-fs-backend";
```
4. Initialize i18next with the FS backend:
```typescript
use(I18NexFsBackend).init({...})
```
5. Run in Firebase Functions Emulator or deploy

## Expected behavior

The import should work at runtime, and not end up in an undefined module.

## Notes

This might be related to this issue: https://github.com/Microsoft/TypeScript/issues/13017

I recognize that setting up Firebase and Firebase Functions might be a big hurdle for reproduction, so I'm offering to do some screen sharing to be able to debug right with my otherwise running project to help fix this bug.

## Your Environment

- *runtime version*: node 18, firebase-functions 4.3.1
- *i18next version*: 23.2.11
- *i18next-fs-backend version*: 2.1.5
- *os*: I think the Firebase Functions run on Linux images

**Comment by adrai** [comment]
Need something to execute locally...
Beside that try to impirt directly from esm... 

`import I18NexFsBackend from "i18next-fs-backend/esm";`

**Comment by ubuntudroid** [comment]
Thanks for the quick response! 🙏 However, that didn't work. 

But, https://github.com/i18next/i18next-fs-backend/issues/39 just pointed me into the right direction.

Setting `"esModuleInterop": true` fixed it for me. Sorry for not having considered that other bug report before. The error was different from mine, so I thought it wasn't related in the first place. 🤦
