### ISSUE TITLE
Provide example of a .ts or .js file that is supported

### ISSUE THREAD

**Issue by sawyerh** [i18next/i18next-fs-backend#41]
## Documentation issue

The documentation mentions:

> .js/.ts (very limited, checks for exports or export default)

An example of a `.ts` file that _is_ supported would be helpful.

## Motivation

In my testing, I was unable to get a `.ts` file's contents to be recognized, so was unclear if my approach is outside of the "very limited" scope mentioned here.

**Comment by adrai** [comment]
test case: https://github.com/i18next/i18next-fs-backend/blob/master/test/backend.js.js
test file: https://github.com/i18next/i18next-fs-backend/blob/master/test/locales/en/test.js

**Comment by adrai** [comment]
relevant code part: https://github.com/i18next/i18next-fs-backend/blob/57e090672d00268d69e91704f0b0e2c2aaff704f/lib/readFile.js#L73
