### ISSUE TITLE
Resolving correct loadPath path

### ISSUE THREAD

**Issue by Creatium** [i18next/i18next-fs-backend#43]
I am having a very strange issue in production build (Node, ExpressJS, Typescript). Trying to resolve correct path to `locales` folder, which is outside `src` folder (and thus outside `dist` folder after build).

This is the path I am trying to use: `loadPath: path.join(__dirname, "../locales/{{lng}}/{{ns}}.json")`, which in `debug: true` mode shows up correctly. But I still get `ENOENT` error in my logs and the translations are not working.

The error is linking to 127 line on `cjs/readFile.js`, where `fs.readFileSync()` is used. And the error also says that it was unable to open `../locales/en/common.json` file.

So the question is why is it trying to open this kind of path, when debug log shows `loadPath` being full and correct: `/www/wwwroot/website.com/api_folder/locales/{{lng}}/{{ns}}.json` ? Am I missing something?

**Comment by adrai** [comment]
Sorry, not easy to help without a reproducible example...
Check directly on your production server ls tge file etc...

**Comment by Creatium** [comment]
Not sure what that was, but overnight it fixed itself. Must have been a bad case of haunted code :)
