### ISSUE TITLE
Uncought TypeError: Cannot read properties of null (reading 'default') in fs.cjs

### ISSUE THREAD

**Issue by AnnoDomine** [i18next/i18next-fs-backend#48]
Hy there.

I installed the fs-backend plugin to create the translation json files when missing.
But i run into the problem where in the fs.cjs f.default is null. 
I updated i18next and react-i18next to newest stable version.
I also installed fs.

Cleared cache, restarted vscode and laptop, etc.

Nothing helps.

## Your Environment

- *runtime version*: node 21x
- *i18next version*:  21.10.0
- *os*:  WSL (Ubuntu)
- *any other relevant information*: Screenshot:
![image](https://github.com/i18next/i18next-fs-backend/assets/6992858/bd0d2438-6c25-494d-a589-32a28f960421)

**Comment by adrai** [comment]
Please provide a minimal reproducible example repository.
I'm not able to reproduce it.

**Comment by AnnoDomine** [comment]
Hey Adrai. Thanks for your fast response.
I could not reproduce it anymore.
But to prepair thin in future i would recomend to add something to avoid this :)
https://github.com/i18next/i18next-fs-backend/blob/master/lib/fs.cjs
This is the file where it happens.
I think `f` was undefined atm and in this case default is undefined too.

**Comment by adrai** [comment]
if f was undefined, then there is something strange in your environment... that's why I asked for a reproducible example

**Comment by AnnoDomine** [comment]
As it is a working environment, i can not share any code parts.
Additional it is an enterprise app so to reproduce it is problematic :(
I am realy sorry. In this way it is okay to close it.
