### ISSUE TITLE
Deno 2.0 no longer supports .cjs module

### ISSUE THREAD

**Issue by NyaightHazard** [i18next/i18next-fs-backend#52]
## 🐛 Bug Report

Deno 2.0 cannot import i18next_fs_backend.
```
error: Expected a JavaScript or TypeScript module, but identified a Cjs module. Importing these types of modules is currently not supported.
  Specifier: https://deno.land/x/i18next_fs_backend@v2.3.2/lib/fs.cjs
    at https://deno.land/x/i18next_fs_backend@v2.3.2/lib/readFile.js:4:24
```
see also https://github.com/denoland/deno/issues/26503

## To Reproduce

import i18next_fs_backend with Deno 2.0+
```ts
import Backend from "https://deno.land/x/i18next_fs_backend@v2.3.2/index.js";
```

## Your Environment

- *runtime version*: i18next_fs_backend v2.3.2, Deno 2.0.2

**Comment by adrai** [comment]
Sorry, that's not possible to remove... since it is used also on non-deno environments... we would need to drop the support for cjs completely...
Maybe this will land sooner or later...

**Comment by NyaightHazard** [comment]
I see. I try to backend-less way in Deno.
But incompatible is still incompatible so I left this issue open.

**Comment by adrai** [comment]
> But incompatible is still incompatible so I left this issue open.
Maybe loading .cjs support will come back in a future Deno version?

btw what do you mean with your side note?
<img width="540" alt="image" src="https://github.com/user-attachments/assets/01c02a0f-a139-4b52-b796-6755c76cda1c">

**Comment by NyaightHazard** [comment]
Why `npm run test:deno` passing? Hmm...
About the sidenote: I mean, Deno 2.0+ cannot import i18next_fs_backend but i18next can. So I'm using i18next with hand-write resource import code instead of i18next_fs_backend for now.

**Comment by adrai** [comment]
I assume `npm run test:deno` works , because if loading a cjs file from a relative path it works... if loaded directly from a http source it somehow fails...
So in theory Deno 2.0 is still able to load .cjs files... they just get blocked when loaded via http

**Comment by NyaightHazard** [comment]
The deno team's worker [said](https://github.com/denoland/deno/issues/26503#issuecomment-2434687082) in my issue:

> you can not import remove files in Deno 2 if they end with .cjs"

I guess it's typo of "... can not import **remote** files ...".
It sounds like intended that works. maybe security reasons?

**Comment by adrai** [comment]
it should work with v2.4.0
