### ISSUE TITLE
Remix - i18n error top level await

### ISSUE THREAD

**Issue by akbarsaputrait** [i18next/i18next-fs-backend#59]
## 🐛 Bug Report

✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

## To Reproduce

I use this template https://github.com/dev-xo/remix-i18n-example/tree/main and upgrade to the latest remix and such this packages:

```json
{
  "i18next": "^24.0.5",
  "i18next-browser-languagedetector": "^8.0.0",
  "i18next-fs-backend": "^2.6.0",
  "i18next-http-backend": "^3.0.1",
  "react-i18next": "^15.1.3",
  "remix-i18next": "^7.0.1"
}
```

## Expected behavior

<img width="1324" alt="Screenshot 2024-12-06 at 02 59 18" src="https://github.com/user-attachments/assets/61488e7a-3ebb-4396-b3da-04c25f70c1ac">

## Your Environment

- *runtime version*: i.e. node 20.15, npm, browser chrome, arc, firefox
- *i18next version*: i.e. ^24.0.5
- *os*: Mac
- Remix 2.15

**Comment by adrai** [comment]
![image](https://github.com/user-attachments/assets/44a6efce-7a24-4907-9085-ed7731cef802)

**Comment by jamalsoueidan** [comment]
@akbarsaputrait did you get it to work, can you share your code example? I'm not directly using i18next-fs-backend, but it throwing error:


X [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/i18next-fs-backend/esm/readFile.js:7:20:
      7 │ var fs = !isDeno ? (await import('node:fs')).default : undefined;
        ╵                     ~~~~~

X [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/i18next-fs-backend/esm/writeFile.js:7:20:
      7 │ var fs = !isDeno ? (await import('node:fs')).default : undefined;
      
      
```json
     "i18next-browser-languagedetector": "^8.0.2",
    "i18next-fs-backend": "2.4.0",
    "i18next-http-backend": "^3.0.1",
```` 


```js

import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";
import { HydratedRouter } from "react-router/dom";

import i18next from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import Backend from "i18next-http-backend/cjs";
import { I18nextProvider, initReactI18next } from "react-i18next";
import { getInitialNamespaces } from "remix-i18next/client";
import i18n from "./i18n";

async function hydrate() {
  await i18next
    .use(initReactI18next)
    .use(LanguageDetector)
    .use(Backend)
    .init({
      ...i18n,
      ns: getInitialNamespaces(),
      backend: { loadPath: "/locales/{{lng}}/{{ns}}.json" },
      detection: {
        // Here only enable htmlTag detection, we'll detect the language only
        // server-side with remix-i18next, by using the `<html lang>` attribute
        // we can communicate to the client the language detected server-side
        order: ["htmlTag"],
        // Because we only use htmlTag, there's no reason to cache the language
        // on the browser, so we disable it
        caches: [],
      },
    });
    
    ````

**Comment by tomStory9** [comment]
After downgrading to v2.4 it didn't fix my top level error. if someone have a solution
