### ISSUE TITLE
Can't resolve fs

### ISSUE THREAD

**Issue by AdrienLemaire** [i18next/i18next-fs-backend#8]
## 🐛 Bug Report
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/home/dori/Projects/Work/Project/v3/client/node_modules/i18next-fs-backend/lib
```

`npm install -D fs` in my repo doesn't solve the issue

## Expected behavior
~fs should be installed with i18next-fs-backend. Can we have it added to the [dependencies](https://github.com/i18next/i18next-fs-backend/blob/master/package.json#L18) list?~

I should be able to run webpack with i18next-fs-backend without error

current code:

src/utilities/i18n.js
```ts
import Backend from "i18next-fs-backend";
import i18n from "i18next";

i18n
  .use(Backend)
  .init({
    backend: {
      loadPath: "../assets/locales/{{lng}}/{{ns}}.json",
    },
    debug: true,
    ns: ["common", "translation"],
    defaultNS: "common",
    lng: "ja",
    fallbackLng: "en",

    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

if (process.env.NODE_ENV !== "production") {
  const { applyClientHMR } = require("i18next-hmr"); // eslint-disable-line
  applyClientHMR(i18n);
}

export default i18n;
```
files in `src/assets/locales`, eg `src/assets/locales/ja/common.json`

## Your Environment

- *runtime version*: v14.4
- *i18next version*: 19.4.4
- *i18next-fs-backend*: 1.0.6
- *os*: Linux

**Comment by adrai** [comment]
fs is a node dependency: https://nodejs.org/dist/latest-v14.x/docs/api/fs.html#fs_file_system
Can you create a reproducable example?

**Comment by jamuhl** [comment]
fs is part of node.js core -> don't use this backend outside of node.js

**Comment by AdrienLemaire** [comment]
You guys are fast ^^
Sorry, just found https://github.com/i18next/i18next-node-fs-backend/issues/215 , closing as off topic

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
